### ISSUE TITLE
Build src and doc jar

### ISSUE THREAD

**Issue by lambdaupb** [anthonynsimon/jurl#1]
I'm not sure if this because of jitpack.io, but I cant download the sources jar for jurl.
This makes debugging and understanding the library more difficult.

Maybe only an option is missing in the gradle build file.

Thanks for the cool library!

**Comment by anthonynsimon** [comment]
Hey I updated the gradle build file and it should include the sources now. Let me know if it worked! Cheers

**Comment by lambdaupb** [comment]
It works ! :)
Thanks for the quick fix.
