### ISSUE TITLE
Dropping trailing question mark

### ISSUE THREAD

**Issue by fommil** [anthonynsimon/jurl#4]
possibly related to #2 but I have some URLs that are not roundtripping, e.g. if there is a trailing `?`

```
scala> import com.anthonynsimon.url.URL
scala> URL.parse("http://example.com/?")
res0: com.anthonynsimon.url.URL = http://example.com/
```

**Comment by fommil** [comment]
also, I have to say, thank you for making and releasing this library!

I discovered that `new URL` in our codebase to validate URLs was a bottleneck and swapping to this library is about 10x more throughput.

Any chance you could publish on Maven Central :smile:

**Comment by anthonynsimon** [comment]
It's great to hear you found the library useful! Thanks to some recently merged changes by @jasonk000  you should find it even more performant now.

I'll take a look at the trailing `?` issue. And yes, I'll try to get it on Maven Central soonish :)
